### ISSUE TITLE
Benchmark is not working in master branch

### ISSUE THREAD

**Issue by meshin-dev** [Fatal1ty/mashumaro#173]
Steps to reproduce (as described in readme):

```bash
git clone https://github.com/Fatal1ty/mashumaro.git                                                                                                    ─╯
cd mashumaro
python3 -m venv env && source env/bin/activate
pip install -e .
pip install -r requirements-dev.txt
./benchmark/run.sh
```

Error:

```bash
Traceback (most recent call last):
  File "/Users/dmitri/projects/mashumaro/benchmark/libs/mashumaro/load.py", line 2, in <module>
    from benchmark.libs.mashumaro.common import Benchmark
  File "/Users/dmitri/projects/mashumaro/benchmark/libs/mashumaro/common.py", line 50, in <module>
    @dataclass(slots=True)
TypeError: dataclass() got an unexpected keyword argument 'slots'
```

**Comment by Fatal1ty** [comment]
@meshin-dev

I guess you’re trying to run them on old Python version. Slots were added in Python 3.10.

**Comment by meshin-dev** [comment]
Yeah, it was on python3.9
Thanks!
