### ISSUE TITLE
JSON encode and decode not commuting

### ISSUE THREAD

**Issue by mynameismon** [Fatal1ty/mashumaro#263]
* mashumaro version: 3.14
* Python version: 3.12
* Operating System: Ubuntu 24.04

### Description

I was trying to use `json_decode` to decode a `NamedTuple` earlier encoded by a `json_decode`

### What I Did

```py
>>> from typing import NamedTuple
>>> from mashumaro.codecs.json import json_encode, json_decode
>>> t = NamedTuple('Hello_Arguments', [('x', int),])
>>> u = NamedTuple('Hello_Arguments', [('x', int),])
>>> json_encode([3.0], t)
'[3.0]'
>>> json_decode(json_encode([3.0], t), u)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mon/.cache/pypoetry/virtualenvs/pykvraft-tzrx1WA_-py3.12/lib/python3.12/site-packages/mashumaro/codecs/json.py", line 97, in json_decode
    return JSONDecoder(shape_type, pre_decoder_func=pre_decoder_func).decode(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in decode
AttributeError: module '__main__' has no attribute 'Hello_Arguments'
```

### Expected Behaviour

```py
>>> json_decode(json_encode([3.0], t), u)
[3.0]
```

**Comment by mynameismon** [comment]
Interestingly, this can be replicated with a single type variable alone. I.e.
```py
>>> json_decode(json_encode([3.0], t), t)
[...]
AttributeError: module '__main__' has no attribute 'Hello_Arguments'
```

Am also able to reproduce this with `JSONEncoder`/`JSONDecoder`.

**Comment by cookiepresence** [comment]
After some experimentation, this seems to be a problem with NamedTuples itself, and not a problem with any encoder/decoder in particular. I have been able to replicate this with MessagePack and YAML as well

**Comment by Fatal1ty** [comment]
@mynameismon you should use the same name for the type variable as the `typename` argument in `NamedTuple`. This is wrong:
```python
t = NamedTuple('Hello_Arguments', [('x', int),])
```
This is correct:
```python
Hello_Arguments = NamedTuple('Hello_Arguments', [('x', int),])
```

If you run mypy on your example you will see what I'm talking about:
```
main.py:3: error: First argument to namedtuple() should be "t", not "Hello_Arguments"  [name-match]
main.py:4: error: First argument to namedtuple() should be "u", not "Hello_Arguments"  [name-match]
```
