### ISSUE TITLE
Problem with function type_name, exact in the __qualname__ attribute

### ISSUE THREAD

**Issue by ZhymabekRoman** [Fatal1ty/mashumaro#36]
Hello. Recently, while adapting my project code to the mashumaro library, I encountered a strange bug. Here is the code itself to play the bug:
```
from enum import Enum
from typing import Set
from dataclasses import dataclass
from mashumaro import DataClassJSONMixin

class testing:
    
    @staticmethod
    def pets():
        
        class PetType(Enum):
            CAT = 'CAT'
            MOUSE = 'MOUSE'

        @dataclass(unsafe_hash=True)
        class Pet(DataClassJSONMixin):
            name: str
            age: int
            pet_type: PetType

        @dataclass
        class Person(DataClassJSONMixin):
            first_name: str
            second_name: str
            age: int
            pets: Set[Pet]


        tom = Pet(name='Tom', age=5, pet_type=PetType.CAT)
        jerry = Pet(name='Jerry', age=3, pet_type=PetType.MOUSE)
        john = Person(first_name='John', second_name='Smith', age=18, pets={tom, jerry})

        dump = john.to_json()
        person = Person.from_json(dump)

testing.pets()

```
I made this code based on an official example. Here is the runtime error itself:
```
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 36, in <module>
  File "<string>", line 16, in pets
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/mashumaro/serializer/base/dict.py", line 21, in __init_subclass__
    raise exc
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/mashumaro/serializer/base/dict.py", line 13, in __init_subclass__
    builder.add_from_dict()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/mashumaro/serializer/base/metaprogramming.py", line 323, in add_from_dict
    self.compile()
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/mashumaro/serializer/base/metaprogramming.py", line 191, in compile
    exec(self.lines.as_text(), globals(), self.__dict__)
  File "<string>", line 43
    kwargs['pet_type'] = value if use_enum else __main__.testing.pets.<locals>.PetType(value)
                                                                      ^
SyntaxError: invalid syntax

[Program finished]
```
The problem seems to be the \_\_qualname\_\_ attribute, which is in the function type_name, of the file helpers.py. I tried to exclude the closure names (name.\<locals\>) that gives the qualname attribute, but failed.

**Comment by Fatal1ty** [comment]
Hello. It won't work this way because mashumaro needs the classes to be accessed on the module import but here the classes `Pet` and `Person` are being created each time `pets` method is called. `__qualname__` attribute allows your classes to be inside other classes but not functions. So, to make this example work you could move the data classes to the global level since they reference each other.

**Comment by ZhymabekRoman** [comment]
Ehhh, okay, thank you
